/**
 * List of valid and available error codes
 */

export const UNKNOWN_ERROR = 'UNKNOWN_ERROR';

export const VALIDATION_ERROR = 'VALIDATION_ERROR';
export const VALIDATION_ERROR_SAMPLE = 'VALIDATION_ERROR_SAMPLE';
export const VALIDATION_ERROR_UNKNOWN_PARAMETER =
  'VALIDATION_ERROR_UNKNOWN_PARAMETER';

export const PING_QUEUE_PROCESSOR_SAMPLE_ERROR =
  'PING_QUEUE_PROCESSOR_SAMPLE_ERROR';
