/**
 * List of valid and available error codes
 */

export const UNKNOWN_ERROR = 'UNKNOWN_ERROR';

export const ERROR_EXCEPTION = 'ERROR_EXCEPTION';
export const ERROR_SAMPLE = 'ERROR_SAMPLE';
export const ERROR_UNKNOWN_PARAMETER = 'ERROR_UNKNOWN_PARAMETER';

export const PING_QUEUE_PROCESSOR_SAMPLE_ERROR =
  'PING_QUEUE_PROCESSOR_SAMPLE_ERROR';
